name: test
on:
  push:
    branches:
      - master
jobs:
  check-for-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Check for test files
        run: |
          if [ -z "$(find . -maxdepth 1 -name "*.test.ts")" ]; then
            echo "No *.test.ts files found" > napaka.txt
          else
            touch napaka.txt
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  test:
    runs-on: self-hosted
    needs: check-for-tests
    strategy:
      fail-fast: false
      matrix:
        bun-version: ["1.0", "1.1", "latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: napaka
          path: .
      - name: Check for errors in tests
        run: |
          if [ -s napaka.txt ]; then
            cat napaka.txt >&2
            exit 1
          fi
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Install deps
        run: bun i
      - name: Run tests
        run: bun run test
